=== Ygarr/urtstats1/src/core/src/main/resources/xml/import_maps.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           jaxb:version="2.0"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
           >

<!-- Type definition -->
  <!-- Map type Enum -->
  <xs:simpleType name="mapType">
      <xs:restriction base="xs:string">
          <xs:enumeration value="TINY"/>
          <xs:enumeration value="SMALL"/>
          <xs:enumeration value="MEDIUM"/>
          <xs:enumeration value="LARGE"/>
      </xs:restriction>
  </xs:simpleType>
  <!--  Type of qualities for content -->
  <xs:simpleType name="nameStr">
      <xs:restriction base="xs:string">
         <xs:minLength value="1" />
         <xs:maxLength value="40" />
      </xs:restriction>
  </xs:simpleType>
<!-- Element structure definition -->
  <xs:element name="urt_map_import">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="maps" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="map" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="fileName" type="nameStr" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="type" type="mapType" minOccurs="1" maxOccurs="1"/>
                    <xs:element name="hasBots" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="images" minOccurs="0" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="image" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:all>
                                <xs:element name="contentURL" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
                              </xs:all>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Ygarr/urtstats1/src/core/src/main/resources/xml/import_maps.xml
<?xml version="1.0" encoding="UTF-8"?>
<urt_map_import 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="import_maps.xsd">
  <maps>
    <map>
      <fileName>blackbridge</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/blackbridge_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/blackbridge_02.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_abbey</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_abbey_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_abbey_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_abbey_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_abbeyctf</fileName>
      <type>LARGE</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_abbeyctf_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_abbeyctf_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_abbeyctf_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_algiers</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_algiers_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_algiers_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_algiers_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_blackhawk</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_blackhawk_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_blackhawk_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_blackhawk_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_blitzkrieg2_bots</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_blitzkrieg2_bots_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_blitzkrieg2_bots_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_blitzkrieg2_bots_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_blitzkrieg_bots</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_blitzkrieg_bots_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_blitzkrieg_bots_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_blitzkrieg_bots_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_bohemia</fileName>
      <type>LARGE</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_bohemia_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_bohemia_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_bohemia_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_city6_bots</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_city6_bots_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_city6_bots_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_city6_bots_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_commune</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_commune_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_commune_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_commune_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_crazychristmas</fileName>
      <type>LARGE</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_crazychristmas_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_crazychristmas_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_crazychristmas_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_eyasarcade</fileName>
      <type>TINY</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_eyasarcade_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_eyasarcade_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_eyasarcade_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_facade_b5a</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_facade_b5a_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_facade_b5a_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_facade_b5a_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_inferno_b3</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_inferno_b3_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_inferno_b3_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_inferno_b3_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_iran3</fileName>
      <type>SMALL</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_iran3_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_iran3_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_iran3_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_iran3_u1</fileName>
      <type>SMALL</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_iran3_u1_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_iran3_u1_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_iran3_u1_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_metro_beta1</fileName>
      <type>LARGE</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_metro_beta1_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_metro_beta1_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_metro_beta1_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_nepal</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_nepal_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_nepal_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_nepal_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_paris_v2</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_paris_v2_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_paris_v2_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_paris_v2_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_prague_v2</fileName>
      <type>MEDIUM</type>
      <images>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_prague_v2_01.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_prague_v2_02.jpg</contentURL></image>
        <image><contentURL>file:///home/ghost/projects/urt-stats/.unversioned/maps/ut4_prague_v2_03.jpg</contentURL></image>
      </images>
    </map>
    <map>
      <fileName>ut4_slumwar</fileName>
